### ISSUE TITLE
Source not buildable

### ISSUE THREAD

**Issue by Prathamk07** [Project-PixelStar/manifest#2]
[ 33% 1/3] converting Android.bp files to BUILD files at out/soong/bp2build
FAILED: out/soong/bp2build_files_marker
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --bp2build_marker out/soong/bp2build_files_marker --globListDir bp2build_files --globFile out/soong/globs-bp2build_files.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.bp2build_files Android.bp
error: external/libncurses/Android.bp:3:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:10:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:17:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:24:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:31:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:38:9: unrecognized property "srcs"
error: external/bash/Android.bp:3:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:45:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:52:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:59:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:66:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:73:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:80:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:87:9: unrecognized property "srcs"
error: external/libncurses/Android.bp:94:9: unrecognized property "srcs"
error: system/logging/logd/Android.bp:82:13: unrecognized property "aidl.libs"
error: system/logging/logd/Android.bp:123:13: unrecognized property "aidl.libs"
error: external/vim/Android.bp:9:9: unrecognized property "srcs"
error: external/vim/Android.bp:18:9: unrecognized property "srcs"
error: external/vim/Android.bp:27:9: unrecognized property "srcs"
error: external/vim/Android.bp:36:9: unrecognized property "srcs"
error: external/vim/Android.bp:45:9: unrecognized property "srcs"
error: external/vim/Android.bp:54:9: unrecognized property "srcs"
error: external/vim/Android.bp:63:9: unrecognized property "srcs"
error: hardware/libhardware/Android.bp:129:17: unrecognized property "target.non_apex"
13:50:56 soong bootstrap failed with: exit status 1

**Comment by incycledream** [comment]
Is that Android 14?

**Comment by incycledream** [comment]
It's not ready to be buildable until we merge QPR2. Currently, we don't have time to merge it whatsoever

**Comment by stellessia** [comment]
It's not ready to be buildable until we merge QPR2. Currently, we don't have time to merge it whatsoever (EDIT: Mudit actually started doing some work)
